# Generated by Django 4.1.7 on 2023-05-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="slug",
            field=models.SlugField(default=True),
        ),
    ]
