# Generated by Django 4.1.7 on 2023-05-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0002_entry_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="slug",
        ),
    ]
